import type { Metadata } from "next";
import { Open_Sans, Inter } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "framer-motion";
import ObserverProvider from "./context/ObserverContext";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

const InterFont = Inter({
  variable: "--inter",
  subsets: ["latin"],
});

const OpenSans = Open_Sans({
  variable: "--open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${OpenSans.variable} ${InterFont.variable}`}>
      <body>
        <ObserverProvider>
          <Navbar />
          <AnimatePresence mode="wait">{children}</AnimatePresence>
          <Footer />
        </ObserverProvider>
      </body>
    </html>
  );
}
