[build]
    functions="functions"
    publish="assets"
[functions]
  external_node_modules = ["express", "express-react-views", "react", "react-dom", "serverless-http"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true