[build]
    functions="functions"
    publish="assets"
[functions]
  external_node_modules = ["express"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true